#!/usr/bin/env ruby
#                                                                              #
#                                                         :::      ::::::::    #
#    google.rb                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mravenel <mravenel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/02/06 13:29:06 by mravenel          #+#    #+#              #
#    Updated: 2015/02/06 13:53:43 by mravenel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


Chrome = "\"Google Chrome.app\""
BaseUrl = "http://www.google.fr/search?q="
Option = "-a"
Bin = "open"

@ExecString = Bin + " " + Option + " " + Chrome + " " + BaseUrl

ARGV.each do|a|
  a.split(" ").each do |b|
     @ExecString += b + "+"
  end
end 
@ExecString = @ExecString.chomp('+')

exec(@ExecString)
